"""Add year genre cover_url to albums

Revision ID: 4fcb24bdf794
Revises: 
Create Date: 2025-11-26 19:58:11.735697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fcb24bdf794'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('genre', sa.String(length=100), nullable=True))
    op.add_column('albums', sa.Column('cover_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'cover_url')
    op.drop_column('albums', 'genre')
    op.drop_column('albums', 'year')
    # ### end Alembic commands ###
